import 'package:fitandfitness/src/models/exercise/strength/experience_level.dart';
import 'package:fitandfitness/src/models/exercise/strength/motion_type.dart';
import 'package:fitandfitness/src/models/exercise/strength/muscle_group.dart';
import 'package:fitandfitness/src/models/exercise/strength/strength_exercise.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final abdominalsLowerStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.abdominalsLower) ??
            false,
      )
      .toList(),
);

final abdominalsObliquesStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.abdominalsObliques) ??
            false,
      )
      .toList(),
);

final abdominalsTotalStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.abdominalsTotal) ??
            false,
      )
      .toList(),
);

final abdominalsUpperStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.abdominalsUpper) ??
            false,
      )
      .toList(),
);

final backLatissimusDorsiStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.backLatissimusDorsi) ??
            false,
      )
      .toList(),
);

final backLatDorsiOrRhomboidsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups
                ?.contains(MuscleGroup.backLatDorsiOrRhomboids) ??
            false,
      )
      .toList(),
);

final bicepsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.biceps) ?? false,
      )
      .toList(),
);

final calvesGastrocnemiusStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.calvesGastrocnemius) ??
            false,
      )
      .toList(),
);

final calvesSoleusStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.calvesSoleus) ?? false,
      )
      .toList(),
);

final chestPectoralisStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.chestPectoralis) ??
            false,
      )
      .toList(),
);

final legsHamstringsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.legsHamstrings) ??
            false,
      )
      .toList(),
);

final legsQuadricepsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.legsQuadriceps) ??
            false,
      )
      .toList(),
);

final lowerBackErectorSpinaeStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups
                ?.contains(MuscleGroup.lowerBackErectorSpinae) ??
            false,
      )
      .toList(),
);

final shouldersDeltsOrTrapsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups
                ?.contains(MuscleGroup.shouldersDeltsOrTraps) ??
            false,
      )
      .toList(),
);

final shouldersRotatorCuffStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.shouldersRotatorCuff) ??
            false,
      )
      .toList(),
);

final tricepsStrengthExerciseProvider = Provider(
  (ref) => ref
      .read(strengthExerciseProvider)
      .where(
        (exercise) =>
            exercise.muscleGroups?.contains(MuscleGroup.triceps) ?? false,
      )
      .toList(),
);
final strengthExerciseProvider = Provider(
  (ref) => const [
    StrengthExercise(
      name: "Full reverse crunch",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline hip thrust",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline reverse crunch",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying hip thrust",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse crunch",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse medicine ball crunch",
      muscleGroups: [MuscleGroup.abdominalsLower],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating heel touch",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-knee medicine ball hip rotation",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable chop",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cross crunch",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cross crunch w/ medicine ball",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline cross sit-up",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline sit-up w/ twist",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse cable chop",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated medicine ball twist",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Trunk rotator",
      muscleGroups: [MuscleGroup.abdominalsObliques],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Ab cycle",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Front plank (from knees)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Front plank (from toes)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Front plank (tripod - 1 arm and 2 legs or 2 legs and 1 arm)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Kneeling ab rollout",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Medicine ball v-up",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Side-plank (from knees)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Side-plank (from toes)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Side-plank (hip lift)",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.static,
      isPreset: true,
    ),
    StrengthExercise(
      name: "V-up",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Weighted v-up",
      muscleGroups: [MuscleGroup.abdominalsTotal],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent knee sit-up",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-knee crunch",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Crunch",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline crunch",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline sit-up",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Heel touch",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Sit-up",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Weighted crunch",
      muscleGroups: [MuscleGroup.abdominalsUpper],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Assisted pull-up",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Close-grip lat pulldown",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Inverted pull-up",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lat pulldown",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pull-up",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse-grip lat pullown",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse-grip pull-up",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "V-bar pull-up",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Wide-grip lat pulldown",
      muscleGroups: [MuscleGroup.backLatissimusDorsi],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over alternating dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over barbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over hammer dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over long barbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over reverse-grip barbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over single-arm long barbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "One arm dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse incline dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Rope cable row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated cable row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm cable row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm dumbbell row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm lat pulldown",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Standing cable row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Standing single-arm cable row",
      muscleGroups: [MuscleGroup.backLatDorsiOrRhomboids],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bicep curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bottom/top/full curls",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Concentration dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cross body hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Ez-bar curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline alternating dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline alternating hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Kneeling cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying double biceps cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying high cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead double biceps cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead rope cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher barbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher ez-bar curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher hammer dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Preacher single-arm dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Rope cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated alternating curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated alternating hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated dumbbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated hammer curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm barbell curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm cable curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm dumbbell curl w/ incline bench",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Spider curl",
      muscleGroups: [MuscleGroup.biceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell calf raise",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Calf press",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Calf raise - seated",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Calf raise - standing",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell calf raise",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg calf press",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg dumbbell calf raise",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Smith machine calf raise",
      muscleGroups: [MuscleGroup.calvesGastrocnemius],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated calf raise",
      muscleGroups: [MuscleGroup.calvesSoleus],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated single-leg calf raise",
      muscleGroups: [MuscleGroup.calvesSoleus],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable crossover",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Chest press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Close-grip feet-up bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline dumbbell fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline smith machine bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell chest press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Elevated push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Feet-up bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Flat bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Floor press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "High cable crossover",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline alternating dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline barbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline cable fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline dumbbell fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline hammer dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline single-arm dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline smith machine bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline twisting dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline twisting dumbbell fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Kneeling push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Low cable crossover",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine vertical bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Medicine ball crossover push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pec deck",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pec deck fly",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Smith machine bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Smith machine incline bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Twisting dumbbell bench press",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Wide-grip push-up",
      muscleGroups: [MuscleGroup.chestPectoralis],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-knee single-leg hip lift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Deadlift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Elevated hip lift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Elevated single-leg hip lift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Hip lift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Leg curl",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying alternating leg curl",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying leg curl",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying single-leg curl",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated leg curl",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg hip lift",
      muscleGroups: [MuscleGroup.legsHamstrings],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Air Squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating leg extension",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell diagonal lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell hack squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell reverse lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell side lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell split squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell step-up",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell walking lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Box squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bulgarian split squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Diagonal lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell diagonal lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell reverse lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell side lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell split squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell step-up",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell walking lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Forward lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Front squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Goblet squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Hack squat machine",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lateral barbell squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lateral barbell step-up",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lateral squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lateral step-up",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Leg extension",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Leg press",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying machine squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine hack squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pause squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Safety bar squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm barbell side squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm dumbbell side squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg barbell squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg box squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg dumbbell box squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg dumbbell squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg extension",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-leg squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Smith machine squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Split squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Squat",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Step-up",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Walking lunge",
      muscleGroups: [MuscleGroup.legsQuadriceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Alternating superman",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Back raise",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Deficit deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Fat bar deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pause deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Quadruped alternating superman",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Rack pull",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Romanian deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Snatch grip deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Stiff-legged deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Sumo deadlift",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Superman",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Superman hold",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Trap bar deadlift with high handles",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Trap bar deadlift with low handles",
      muscleGroups: [MuscleGroup.lowerBackErectorSpinae],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Arnold dumbbell press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell front raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Barbell shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over cable rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bent-over dumbbell rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable front raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable lateral raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell alternating shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell front raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell lateral raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell twisting shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Front plate raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Kneeling single-arm cable rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying dumbbell external rotation",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying dumbbell rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying single-arm dumbbell rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Pec deck real delt extensions",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse incline dumbbell rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated dumbbell rear delt elbow raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Seated dumbbell rear delt raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm cable lateral raise",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm dumbbell shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Smith machine shoulder press",
      muscleGroups: [MuscleGroup.shouldersDeltsOrTraps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Band pull-aparts",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Cable external rotation",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell external rotation",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell lateral raise",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Face pulls",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Internal cable rotation",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse cable crossover",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Scapular wall slides",
      muscleGroups: [MuscleGroup.shouldersRotatorCuff],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.pull,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Assisted dips",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Bench dips",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Close-grip bench press",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline ez-bar tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline single dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Decline single-arm dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Diamond push-up",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dips",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Dumbbell kickback",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Forward lean dips",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Incline ez-bar tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Kneeling cable triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Leaning overhead tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Low cable triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying cable triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying ez-bar triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying overhead ez-bar tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying reverse ez-bar triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying single dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying single-arm dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Lying tricep extensions",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Machine dips",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead dumbbell triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead ez-bar triceps extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead rope cable tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead single dumbbell tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead single-arm cable tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Overhead single-arm dumbbell tricep extension",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Reverse tricep push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.advanced,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Rope triceps push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm towel triceps push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Single-arm triceps push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.intermediate,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Towel triceps push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Tricep extensions",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "Tricep push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
    StrengthExercise(
      name: "V-bar tricep push-down",
      muscleGroups: [MuscleGroup.triceps],
      experienceLevel: ExperienceLevel.beginner,
      motionType: MotionType.push,
      isPreset: true,
    ),
  ],
);
